### ISSUE TITLE
witgen: speedup evm assignment for big k (20)

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#230]
so slow..

**Comment by jonathanpwang** [comment]
Can you try making a flamegraph to see some initial profiling? 

It's also hard to profile halo2 because of all the extra setup steps, but you can modify the local halo2 `create_proof` to not do anything after calling `synthesize`. 

Here are some notes of mine on how to isolate `synthesize` calls:
```
cargo bench --bench <BENCH NAME> --no-run"
perf record --call-graph dwarf,16384 -e cpu-clock -F 997 target/release/deps/<BEGINS WITH BENCH NAME>
perf script | inferno-collapse-perf > stacks.folded
grep create_proof stacks.folded | grep synthesize > perf_synthesize.out
```

In order to run `inferno-collapse-perf` you need to install

```
cargo install inferno
```

This is a compiled version of the flamegraph script `stackcollapse-perf.pl`, which was originally a perl script and hence probably slower.
The last command will grep for only functions in `synthesize` called from within `create_proof` because we only want to profile witness generation. You can put `create_proof` or something else for more general profiling. Use `perf script` instead of `perf report` because `perf report` seems to truncate the call chain of stack traces.

```
inferno-flamegraph perf_synthesize.out > flamegraph.svg
```

This is based on notes from: https://gist.github.com/dlaehnemann/df31787c41bd50c0fe223df07cf6eb89

In linux-5.15 there were some issues with slow `perf`. I fixed it by following https://michcioperz.com/post/slow-perf-script/ and downloading the entire linux-5.19 source. When building `perf` from source, make sure to follow https://www.brendangregg.com/perf.html#Building and install dependencies so dwarf support is on. Make sure you are using the correct version by checking `perf -v`.

**Comment by lispc** [comment]
using parallel witness assignment helps a lot
