### ISSUE TITLE
bug: insufficient balance can also be caused by create

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#354]
### Describe the bug

not only call. Use Call<7> to process all ErrInsufficientBalance is wrong.

**Comment by roynalnaruto** [comment]
Currently we only use a dummy gadget for `InsufficientBalance` error. Since this error can come in 4 opcodes: `CALL`, `CALLCODE`, `CREATE` and `CREATE2`, we can't use the `CallOpGadget<F>`.

We can create a new gadget `ErrorInsufficientBalance<F>` and handle cases for the above opcodes, similarly handling the bus-mapping logic via a separate `InsufficientBalance` struct.

This also means, we can remove the `insufficient_balance` check from the `CallOpGadget` because such errors will not be handled through that gadget. What do you think @lispc

**Comment by lispc** [comment]
i am not sure.. I remember previous why ErrInsufficientBalance (of call) handled inside CallGadget is becuase ErrInsufficientBalance share many codes with CallGadget so the goal is to avoid same codes in 2 gadgets.

Not sure whether it is good to make a standalone InsufficientBalanceGadget, or handle Err InsufficientBalance inside CreateGadget too.
