### ISSUE TITLE
testool improvements

### ISSUE THREAD

**Issue by lispc** [scroll-tech/zkevm-circuits#820]
### Tool itself

3. use the "defines asm" ignored tests
1. use the "solidity" ignored tests

### Cases

1. check why disabled hash precompiles can pass testing? No post state check? @kunxian-xia 
6. check whether there is pairing len > 4. @kunxian-xia 
7. why base fee did not report err? (skipped?)

**Comment by lispc** [comment]
create2collisionCode_d0_g0_v0 : inside l2 trace, when create2collision occures, we need to record codehash to prove collision..

**Comment by kunxian-xia** [comment]
1. Because we did not init `ArchimedesBlock` in https://github.com/scroll-tech/zkevm-circuits/blob/develop/geth-utils/l2geth/trace.go#L127-L144. 
<img width="741" alt="image" src="https://github.com/scroll-tech/zkevm-circuits/assets/1082586/6a5c33ca-d09d-4a68-a357-419345f9c3b9">
     
 This means that the tracer does not return error when hash precompiles are called. 

![image](https://github.com/scroll-tech/zkevm-circuits/assets/1082586/d05f35ad-cd67-4eb8-8772-84697fc9cd59)

 Since we do not have any gadget to handle hash precompile, the step of state `PrecompileBlake2f` is not constrained at all.

3. The max pairs in the test cases of ec_pairing is 3.

**Comment by lispc** [comment]
1. i see. seems it is better we have more constraints (a) hash precompiles must fail (b) PrecompileFailedGadget can only be used handle hash precompiles.
3. how did you found that? re-run tests and grep logs?

**Comment by kunxian-xia** [comment]
> how did you found that? re-run tests and grep logs?

Yeah. Since some test cases like `CALLBlake2f_d4_g0_v0` expect to have storage changes, then I run the test again and find the stack's top is 1 (should be 0) after callop.

> seems it is better we have more constraints

Sure, we should add constraints in callop.rs to require that next step's state transits to `PrecompileFailed`.

**Comment by kunxian-xia** [comment]
> check whether there is pairing len > 4: how did you found that? re-run tests and grep logs?

yes, I run test cases whose id contains `ecpairing` again and print out the number of pairs (`call_data_length / 192`) it has.
